[DESCRIPTION]
The dataharvester-systemwriter is a simple tool to call the dataharvester's systemwriter
from the commandline.

[EXAMPLES]

  dataharvester-systemwriter

[AUTHOR]
Written by Wolfgang Waltenberger, Herbert Valerio Riedel, and Gerald Richter.

[COPYRIGHT]
Copyright \[co] 2007 Wolfgang Waltenberger <waldi@teilchen.at>

This is free software; see the source for copying conditions.  There is NO warranty; not even for MER-
CHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[REPORTING BUGS]
There are probably still many bugs in the various backends. Report them to Wolfgang Waltenberger <waldi@teilchen.at>.

[SEE ALSO]
For further information see http://harvest.teilchen.at.
