[DESCRIPTION]
The dataharvester-converter is a simple tool to convert "hierarchic tuples" from one file format to another;
for more complicated actions, such as filtering the data, refer to the C++ API or the python interface.

[EXAMPLES]

Merge a.root, b.txt.gz and write the content into c.hdf:

  dataharvester-converter a.root b.txt.gz c.hdf

[AUTHOR]
Written by Wolfgang Waltenberger, Herbert Valerio Riedel, and Gerald Richter.

[COPYRIGHT]
Copyright \[co] 2007 Wolfgang Waltenberger <waldi@teilchen.at>

This is free software; see the source for copying conditions.  There is NO warranty; not even for MER-
CHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[REPORTING BUGS]
There are probably still many bugs in the various backends. Report them to Wolfgang Waltenberger <waldi@teilchen.at>.

[SEE ALSO]
For further information see http://harvest.teilchen.at.
